language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -qq ppa:tehnick/leechcraft-unstable
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq leechcraft-unstable
script: mkdir build && cd build && cmake ../src && make
