language:
  - cpp
compiler:
  - g++
  - clang++
before_install:
  - sudo add-apt-repository ppa:tehnick/leechcraft-unstable
  - sudo apt-get update
  - sudo apt-get build-dep
script:
  - mkdir build 
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=Debug ../src 
  - cd build 
  - make 
  - make install
